# Generated by Django 3.2.19 on 2023-05-23 10:46

from django.db import migrations
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20230522_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='/default_image.jpg', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='background',
            field=djrichtextfield.models.RichTextField(max_length=500),
        ),
    ]
